### ISSUE TITLE
Probem

### ISSUE THREAD

**Issue by Duzo12** [Duzo12/APPR-2018-19#4]
V nalogi sem naletel na problem. Rad bi izbrisal vse presledke v tabeli Izobrazba. V stolpcu Drzava so nekatere države napisane s presledkom zato mi R ne združi tabel po besedi Drzava. probal sem s funkcijo:
gsub(" ", "", tabelaIzobrazba), vendar nisem bil uspešen. Hvala za odgovor.

**Comment by MarvinHerzog** [comment]
Zgleda so presledki v tvojih stolpcih tipa `\u00a0`, gre se za posebne [unicode no-break space](http://www.fileformat.info/info/unicode/char/00a0/index.htm) tipe presledkov, ki jih je treba obravnavati posebej, saj ne gre za ASCII znak. Teh presledkov se lahko znebiš takole:

```
tabelaIzobrazba$Drzava <- gsub("^[[:space:]]*", "", tabelaIzobrazba$Drzava)
```

**Comment by jaanos** [comment]
Izgleda, da rešitev, ki jo je podal @MarvinHerzog, ne deluje povsod. Da zagotovo pobrišeš tudi nedeljivi presledek, uporabi regularni izraz `"^[[:space:]\u00a0]*"`.

Mimogrede, svetujem, da v naslovu issuejev malo bolje opišeš, za kaj se gre - da ne bo vsakemu naslov *Problem*.
